version: "3.7"

services:
  led-strip-controller:
    image: $DOCKER_HUB_USERNAME/iot-control-center:led-controller
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_IP: ${MONGO_DB_IP}
